config/routes.rb
Rails.application.routes.draw do
  get 'landmarks/edit'
  get 'landmarks/index', :to => "landmarks#index", :as => "landmark"
  get '/landmarks/new', :to => "landmarks#new", :as => "new_landmark"
  get 'landmarks/show'
  post '/landmarks/create', :to =>"landmarks#create", :as => "create_landmark"
  get 'landmarks/update'
  get 'locations/edit'
  get '/locations/index', :to => "locations#index", :as => "locations"
  get '/locations/new', :to => "locations#new", :as => "new_location"
  post '/locations/create', :to => "locations#create", :as => "create_location"
  get 'locations/show'
  resources :places, except: [:update, :edit, :destroy]
root 'places#index'
  get 'places/edit'
  get 'places/update'
  get 'places/index'
  get 'places/new'
  get 'places/create'
  get '/products/new', :to => "products#new", :as => "new_products"
  get '/products/index', :to => 'products#index', :as => "products"
  get '/products/edit/:id', :to => 'products#edit', :as => "edit_products" 
  patch '/products/update/:id', :to => "products#update", :as => "update_products"
  post 'products/create', :to => "products#create", :as => "create_products"
  # get 'products/some_date', :to => "products#some_date", :as => "some_date_products"
  get '/customers/index', :to => "customers#index", :as => "customers"
  get '/customers/show/:id', :to => "customers#show", :as => "customer_orders"
  get '/customers/new', :to => "customers#new", :as => "new_customer"
  get '/customers/user', :to => "customers#user", :as => "user_customer"
  get '/customers/edit/:id', :to => "customers#edit", :as => "edit_customer"
  patch '/customers/update/:id', :to => "customers#update", :as => "update_customer"
  post '/customers/create', :to => "customers#create", :as => "create_customer"
  # get 'customers/show/:id', :to => 'customers#show', :as => 
  get '/orders/new', :to => "orders#new", :as => 'new_orders'
  post '/orders/create', :to => "orders#create", :as => 'create_order'
  # get 'orders/edit'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/users/new', :to => "users#new", :as => "new_users"
  get '/users/show', :to => "users#show", :as => "show_users"
  # get 'users/edit'
  # get 'users/update'
  # get 'users/create'
end

app/models/landmark.rb
class Landmark < ApplicationRecord
    
    geocoded_by :full_address
    after_validation :geocode    

    def full_address
      [:village, :mandal, :district, :state, :country].join(', ')
    end
end

app/controllers/landmarks_controller.rb
class LandmarksController < ApplicationController
  def index
    @landmarks = Landmark.all
  end
  def edit
  end

  def new
    @landmark = Landmark.new
  end

  def show
  end

  def create
    @landmark = Landmark.new(landmark_params)
    @landmark.save
    redirect_to landmark_path
  end

  def update
  end

  private

  def landmark_params
    params.require(:landmark).permit(:name, :age, :phone_no, :villae, :mandal, :district, :state, :country)
  end

end
# , :village, :mandal, :district, :state, :country

app/helpers/landmarks_helper.rb
module LandmarksHelper
end

app/views/landmarks/_form.html.erb
<div class ='form-group'>
<%= c.label :name, 'Name' %>
 <%= c.text_field :name, :class => "form-control" %>
</div>
<div class ='form-group'>
<%= c.label :age, 'Age' %>
 <%= c.text_field :age, :class => "form-control" %>
</div>
<div class ='form-group'>
<%= c.label :phone_no, 'Phone No' %>
 <%= c.text_field :phone_no, :class => "form-control" %>
</div>
<div class ='form-group'>
<%= c.label :village, 'Village' %>
 <%= c.text_field :village, :class => "form-control" %>
</div>
<div class = 'form-group'>
<%= c.label :mandal, 'Mandal' %>
<%= c.text_field :mandal, :class => "form-control" %>
</div>
<div class = 'form-group'>
<%= c.label :district, 'District' %>
<%= c.text_field :district, :class => "form-control" %>
</div>
<div class = 'form-group'>
<%= c.label :state, "State" %>
<%= c.text_field :state, :class => "form-control" %>
</div>   
<div class = 'form-group' >
<%= c.label :country, "country" %>
<%= c.text_field :country, :class => "form-control" %>
</div>
<%= c.submit "submit", :class => 'btn btn-success' %>

app/views/landmarks/create.html.erb
<h1>Landmarks#create</h1>
<p>Find me in app/views/landmarks/create.html.erb</p>

app/views/landmarks/edit.html.erb
<h1>Landmarks#edit</h1>
<p>Find me in app/views/landmarks/edit.html.erb</p>

app/views/landmarks/index.html.erb
<div class = "table-responsive">
<table class='table table-striped'>
<%= link_to "new", new_landmark_path, :class => 'btn btn-primary'%>
<h1>Address</h1>

<tr>
<th>Name</th>
<th>Age</th>
<th>Phone_no</th>
<th>Address</th>

</tr>
<% @landmarks.each do |landmark| %>    
    <tr>
    <td><%= landmark.name%></td>
    <td><%= landmark.age%></td>
    <td><%= landmark.phone_no%></td>
    <td><%= landmark.address%></td>   
    </tr>   
    <% end %>

</table>
</div>

app/views/landmarks/new.html.erb
<%= form_with model: @landmark, url: create_landmark_path do |c| %>
    <%= render partial: 'form', locals: {c: c} %>
 <% end %>

app/views/landmarks/show.html.erb
<h1>Landmarks#show</h1>
<p>Find me in app/views/landmarks/show.html.erb</p>

app/views/landmarks/update.html.erb
<h1>Landmarks#update</h1>
<p>Find me in app/views/landmarks/update.html.erb</p>