config/routes.rb
Rails.application.routes.draw do
  get 'landmarks/edit'
  get 'landmarks/index', :to => "landmarks#index", :as => "landmark"
  get '/landmarks/new', :to => "landmarks#new", :as => "new_landmark"
  get 'landmarks/show'
  post '/landmarks/create', :to =>"landmarks#create", :as => "create_landmark"
  get 'landmarks/update'
  get 'locations/edit'
  get '/locations/index', :to => "locations#index", :as => "locations"
  get '/locations/new', :to => "locations#new", :as => "new_location"
  post '/locations/create', :to => "locations#create", :as => "create_location"
  get 'locations/show'
  resources :places, except: [:update, :edit, :destroy]
root 'places#index'
  get 'places/edit'
  get 'places/update'
  get 'places/index'
  get 'places/new'
  get 'places/create'
  get '/products/new', :to => "products#new", :as => "new_products"
  get '/products/index', :to => 'products#index', :as => "products"
  get '/products/edit/:id', :to => 'products#edit', :as => "edit_products" 
  patch '/products/update/:id', :to => "products#update", :as => "update_products"
  post 'products/create', :to => "products#create", :as => "create_products"
  # get 'products/some_date', :to => "products#some_date", :as => "some_date_products"
  get '/customers/index', :to => "customers#index", :as => "customers"
  get '/customers/show/:id', :to => "customers#show", :as => "customer_orders"
  get '/customers/new', :to => "customers#new", :as => "new_customer"
  get '/customers/user', :to => "customers#user", :as => "user_customer"
  get '/customers/edit/:id', :to => "customers#edit", :as => "edit_customer"
  patch '/customers/update/:id', :to => "customers#update", :as => "update_customer"
  post '/customers/create', :to => "customers#create", :as => "create_customer"
  # get 'customers/show/:id', :to => 'customers#show', :as => 
  get '/orders/new', :to => "orders#new", :as => 'new_orders'
  post '/orders/create', :to => "orders#create", :as => 'create_order'
  # get 'orders/edit'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/users/new', :to => "users#new", :as => "new_users"
  get '/users/show', :to => "users#show", :as => "show_users"
  # get 'users/edit'
  # get 'users/update'
  # get 'users/create'
end

app/models/customer.rb
class Customer < ApplicationRecord
    has_many :orders

    geocoded_by :full_address
    after_validation :geocode

    def full_address
        [:village, :mandal, :district, :state, :country].join(', ')
    end

    

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find_by_id(params[:id])
    @customer_orders = @customer.orders    
  end

  def new
    @customer = Customer.new
  end
  def user
  end
  
  def create
    @customer = Customer.new(customer_params)
    @customer.save
    redirect_to customers_path 
  end

  def edit
    @customer = Customer.find(params[:id])
    # @customer.update(customer_params)
    # redirect_to customers_path
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to customers_path
  end 

  private

  def customer_params
    params.require(:customer).permit(:name, :email, :mobile, :village, :mandal, :district, :state, :country)
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<div class ='form-group' id = 'edit123'>
<%= c.label :name, 'Name' %>
 <%= c.text_field :name, :class => "form-control" %>
</div>
<div class = 'form-group'>
<%= c.label :Email, 'Email' %>
<%= c.text_field :email, :class => "form-control" %>
</div>
<div class = 'form-group'>
<%= c.label :mobile, 'Mobile No' %>
<%= c.text_field :mobile, :class => "form-control" %>
</div> 
<div class = 'form-group'>
<%= c.label :village, "Village" %>
<%= c.text_field :village, :class => "form-control" %>
</div>   
<div class = 'form-group'>
<%= c.label :mandal, "Mandal" %>
<%= c.text_field :mandal, :class => "form-control" %>
</div>   
<div class = 'form-group'>
<%= c.label :district, "District" %>
<%= c.text_field :district, :class => "form-control" %>
</div> 
<div class = 'form-group'>
<%= c.label :state, "State" %>
<%= c.text_field :state, :class => "form-control" %>
</div>   
<div class = 'form-group'>
<%= c.label :country, "Country" %>
<%= c.text_field :country, :class => "form-control" %>
</div>   
<div class = 'form-group' >
<%= c.label :file, "File Upload" %>
<%= c.file_field :file %>
</div>
<%= c.submit "submit", :class => 'btn btn-success' %>

app/views/customers/edit.html.erb
<%= form_with model: @customer, url: edit_customer_path do |c| %>
 
    <%= render partial: 'form', locals: {c: c} %>
 <% end %>

app/views/customers/index.html.erb
<html> 
<body>
<style>

</style>
<div class = 'customer' >
<div class = "table-responsive">
<table class='table table-striped'>
<%= link_to "new", new_customer_path, :class => 'btn btn-primary'%>
<h1>Customers</h1>

<tr>
<th>Id</th>
<th>Name</th>
<th>Email</th>
<th>Mobile</th>
<th>Address</th>
<th></th>
<th></th>
</tr>
<% @customers.each do |customer| %>    
    <tr>
    <td><%= customer.id %></td>
    <td><%= customer.name %></td>
    <td><%= customer.email %></td>
    <td><%= customer.mobile %></td>
    <td><%= customer.address %></td>
    <td><%= link_to "View", customer_orders_path(customer) %></td>
    <td><%= link_to "edit", edit_customer_path(customer), :class => 'edit_button' %></td>
    </tr>
   
    
    
    <% end %>

</table>
</div>
</div>
</body>
</html> 

app/views/customers/new.html.erb
<%= form_with model: @customer, url: create_customer_path do |c| %>
   <%= render partial: 'form', locals: {c: c} %>
<% end %>

app/views/customers/show.html.erb
<table class = 'table'>
<tr>
<td><%= link_to "Back to customers", customers_path %></td>
<td><%= link_to "Customer Order", new_orders_path %></td>
</tr>
</table>

<h2>Orders of <%= @customer.name %> </h2>

<table  class="table">

<tr>
<th>Customer_id</th>
<th>Product</th>
<th>Quantity</th>
<th>Price</th>
<th>Date</th>

</tr>
<% @customer_orders.each do |order| %>
    <tr>
    <td><%= order.customer_id %></td>
    <td><%= order.product %></td>
    <td><%= order.quantity %></td>
    <td><%= order.price %></td>
    <td><%= order.date %></td>
    
    </tr>
    <% end %>
</table>
</body>

app/views/customers/user_profile.html.erb
<html>
<head>
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->
/***
User Profile Sidebar by @keenthemes
A component of Metronic Theme - #1 Selling Bootstrap 3 Admin Theme in Themeforest: http://j.mp/metronictheme
Licensed under MIT
***/
<style>
body {
  background: #F1F3FA;
}

/* Profile container */
.profile {
  margin: 20px 0;
}

/* Profile sidebar */
.profile-sidebar {
  padding: 20px 0 10px 0;
  background: #fff;
}

.profile-userpic img {
  float: none;
  margin: 0 auto;
  width: 50%;
  height: 50%;
  -webkit-border-radius: 50% !important;
  -moz-border-radius: 50% !important;
  border-radius: 50% !important;
}

.profile-usertitle {
  text-align: center;
  margin-top: 20px;
}

.profile-usertitle-name {
  color: #5a7391;
  font-size: 16px;
  font-weight: 600;
  margin-bottom: 7px;
}

.profile-usertitle-job {
  text-transform: uppercase;
  color: #5b9bd1;
  font-size: 12px;
  font-weight: 600;
  margin-bottom: 15px;
}

.profile-userbuttons {
  text-align: center;
  margin-top: 10px;
}

.profile-userbuttons .btn {
  text-transform: uppercase;
  font-size: 11px;
  font-weight: 600;
  padding: 6px 15px;
  margin-right: 5px;
}

.profile-userbuttons .btn:last-child {
  margin-right: 0px;
}
    
.profile-usermenu {
  margin-top: 30px;
}

.profile-usermenu ul li {
  border-bottom: 1px solid #f0f4f7;
}

.profile-usermenu ul li:last-child {
  border-bottom: none;
}

.profile-usermenu ul li a {
  color: #93a3b5;
  font-size: 14px;
  font-weight: 400;
}

.profile-usermenu ul li a i {
  margin-right: 8px;
  font-size: 14px;
}

.profile-usermenu ul li a:hover {
  background-color: #fafcfd;
  color: #5b9bd1;
}

.profile-usermenu ul li.active {
  border-bottom: none;
}

.profile-usermenu ul li.active a {
  color: #5b9bd1;
  background-color: #f6f9fb;
  border-left: 2px solid #5b9bd1;
  margin-left: -2px;
}

/* Profile Content */
.profile-content {
  padding: 20px;
  background: #fff;
  min-height: 460px;
}
</style>
</head>
<body>
<!--
User Profile Sidebar by @keenthemes
A component of Metronic Theme - #1 Selling Bootstrap 3 Admin Theme in Themeforest: http://j.mp/metronictheme
Licensed under MIT
-->

<div class="container">
    <div class="row profile">
		<div class="col-md-3">
			<div class="profile-sidebar">
				<!-- SIDEBAR USERPIC -->
				<div class="profile-userpic">
					<img src="http://keenthemes.com/preview/metronic/theme/assets/admin/pages/media/profile/profile_user.jpg" class="img-responsive" alt="">
				</div>
				<!-- END SIDEBAR USERPIC -->
				<!-- SIDEBAR USER TITLE -->
				<div class="profile-usertitle">
					<div class="profile-usertitle-name">
						Marcus Doe
					</div>
					<div class="profile-usertitle-job">
						Developer
					</div>
				</div>
				<!-- END SIDEBAR USER TITLE -->
				<!-- SIDEBAR BUTTONS -->
				<div class="profile-userbuttons">
					<button type="button" class="btn btn-success btn-sm">Follow</button>
					<button type="button" class="btn btn-danger btn-sm">Message</button>
				</div>
				<!-- END SIDEBAR BUTTONS -->
				<!-- SIDEBAR MENU -->
				<div class="profile-usermenu">
					<ul class="nav">
						<li class="active">
							<a href="#">
							<i class="glyphicon glyphicon-home"></i>
							Overview </a>
						</li>
						<li>
							<a href="#">
							<i class="glyphicon glyphicon-user"></i>
							Account Settings </a>
						</li>
						<li>
							<a href="#" target="_blank">
							<i class="glyphicon glyphicon-ok"></i>
							Tasks </a>
						</li>
						<li>
							<a href="#">
							<i class="glyphicon glyphicon-flag"></i>
							Help </a>
						</li>
					</ul>
				</div>
				<!-- END MENU -->
			</div>
		</div>
		<div class="col-md-9">
            <div class="profile-content">
			   Some user related content goes here...
            </div>
		</div>
	</div>
</div>
<center>
<strong>Powered by <a href="http://j.mp/metronictheme" target="_blank">KeenThemes</a></strong>
</center>
<br>
<br>
</body>
</html>