config/routes.rb
Rails.application.routes.draw do
  get 'landmarks/edit'
  get 'landmarks/index', :to => "landmarks#index", :as => "landmark"
  get '/landmarks/new', :to => "landmarks#new", :as => "new_landmark"
  get 'landmarks/show'
  post '/landmarks/create', :to =>"landmarks#create", :as => "create_landmark"
  get 'landmarks/update'
  get 'locations/edit'
  get '/locations/index', :to => "locations#index", :as => "locations"
  get '/locations/new', :to => "locations#new", :as => "new_location"
  post '/locations/create', :to => "locations#create", :as => "create_location"
  get 'locations/show'
  resources :places, except: [:update, :edit, :destroy]
root 'places#index'
  get 'places/edit'
  get 'places/update'
  get 'places/index'
  get 'places/new'
  get 'places/create'
  get '/products/new', :to => "products#new", :as => "new_products"
  get '/products/index', :to => 'products#index', :as => "products"
  get '/products/edit/:id', :to => 'products#edit', :as => "edit_products" 
  patch '/products/update/:id', :to => "products#update", :as => "update_products"
  post 'products/create', :to => "products#create", :as => "create_products"
  # get 'products/some_date', :to => "products#some_date", :as => "some_date_products"
  get '/customers/index', :to => "customers#index", :as => "customers"
  get '/customers/show/:id', :to => "customers#show", :as => "customer_orders"
  get '/customers/new', :to => "customers#new", :as => "new_customer"
  get '/customers/user', :to => "customers#user", :as => "user_customer"
  get '/customers/edit/:id', :to => "customers#edit", :as => "edit_customer"
  patch '/customers/update/:id', :to => "customers#update", :as => "update_customer"
  post '/customers/create', :to => "customers#create", :as => "create_customer"
  # get 'customers/show/:id', :to => 'customers#show', :as => 
  get '/orders/new', :to => "orders#new", :as => 'new_orders'
  post '/orders/create', :to => "orders#create", :as => 'create_order'
  # get 'orders/edit'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/users/new', :to => "users#new", :as => "new_users"
  get '/users/show', :to => "users#show", :as => "show_users"
  # get 'users/edit'
  # get 'users/update'
  # get 'users/create'
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
   
  end

  def edit
    @product = Product.find(params[:id])
    # @product.save
    # redirect_to products_path 
  end

  def create
    @product = Product.new(product_params)
    @product.save
    redirect_to products_path 
  end

  def update
    @product = Product.find(params[:id])
    @product.update(product_params)
    redirect_to products_path
  end 


  private
  def product_params
    params.require(:product).permit(:name, :unit, :unit_price, :date)
  end
  
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<div class = 'form-group'>
<%= select("order", "customer_id", Product.all.collect {|p| [ p.name, p.id ] }, { include_blank: 'select Product' }, :class => 'form-control') %>
</div>

<div class = 'form-group'>
    <%= p.label :unit, 'Units' %>
    <%= p.text_field :unit, :class => "form-control" %>
</div>
<div class = 'form-group'>
    <%= p.label :unit_price, 'Unit Price' %>
    <%= p.text_field :unit_price, :class => "form-control" %>
</div>
<div class = 'form-group'>
    <%= p.label :date, "Date" %>
    <%= p.text_field :date, :class => "form-control" %>    
</div>
    <%= p.submit "submit", :class => 'btn btn-success' %>

app/views/products/create.html.erb
<h1>Products#create</h1>
<p>Find me in app/views/products/create.html.erb</p>

app/views/products/edit.html.erb
<%= form_with model: @product, url: update_products_path do |p| %>
    <%= render partial: 'form', locals: {p: p} %>
<% end %>

app/views/products/index.html.erb
<div class = "table-responsive">
    <table class='table table-striped'>
        <%= link_to "new", new_products_path, :class => 'btn btn-primary'%>
        <h1>Products</h1>
        <tr>
            <th>Name</th>
            <th>Units</th>
            <th>Unit Price</th>
            <th>Date</th>
            <th></th>
        </tr>
        <% @products.each do |product| %>    
            <tr>   
                <td><%= product.name %></td>
                <td><%= product.unit %></td>
                <td><%= product.unit_price %></td>
                <td><%= product.date %></td>
                <td><%= link_to "edit", products_path(product), :class => 'edit_button' %></td>
            </tr>
        <% end %>
    </table>
</div>

app/views/products/new.html.erb
<%= form_with model: @product, url: create_products_path do |p| %>
    <%= render partial: 'form', locals: {p: p} %>    
 <% end %>
 