config/routes.rb
Rails.application.routes.draw do
  get 'landmarks/edit'
  get 'landmarks/index', :to => "landmarks#index", :as => "landmark"
  get '/landmarks/new', :to => "landmarks#new", :as => "new_landmark"
  get 'landmarks/show'
  post '/landmarks/create', :to =>"landmarks#create", :as => "create_landmark"
  get 'landmarks/update'
  get 'locations/edit'
  get '/locations/index', :to => "locations#index", :as => "locations"
  get '/locations/new', :to => "locations#new", :as => "new_location"
  post '/locations/create', :to => "locations#create", :as => "create_location"
  get 'locations/show'
  resources :places, except: [:update, :edit, :destroy]
root 'places#index'
  get 'places/edit'
  get 'places/update'
  get 'places/index'
  get 'places/new'
  get 'places/create'
  get '/products/new', :to => "products#new", :as => "new_products"
  get '/products/index', :to => 'products#index', :as => "products"
  get '/products/edit/:id', :to => 'products#edit', :as => "edit_products" 
  patch '/products/update/:id', :to => "products#update", :as => "update_products"
  post 'products/create', :to => "products#create", :as => "create_products"
  # get 'products/some_date', :to => "products#some_date", :as => "some_date_products"
  get '/customers/index', :to => "customers#index", :as => "customers"
  get '/customers/show/:id', :to => "customers#show", :as => "customer_orders"
  get '/customers/new', :to => "customers#new", :as => "new_customer"
  get '/customers/user', :to => "customers#user", :as => "user_customer"
  get '/customers/edit/:id', :to => "customers#edit", :as => "edit_customer"
  patch '/customers/update/:id', :to => "customers#update", :as => "update_customer"
  post '/customers/create', :to => "customers#create", :as => "create_customer"
  # get 'customers/show/:id', :to => 'customers#show', :as => 
  get '/orders/new', :to => "orders#new", :as => 'new_orders'
  post '/orders/create', :to => "orders#create", :as => 'create_order'
  # get 'orders/edit'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/users/new', :to => "users#new", :as => "new_users"
  get '/users/show', :to => "users#show", :as => "show_users"
  # get 'users/edit'
  # get 'users/update'
  # get 'users/create'
end

app/models/place.rb
class Place < ApplicationRecord
    

    geocoded_by :full_address
    after_validation :geocode

    def full_address
        [:city, :state, :country].join(', ')
    end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  # def index
  #   @places = Place.order('created_at DESC')
  # end

  # def new
  #   @place = Place.new
  # end

  # def create
  #   @place = Place.new(place_params)
  #   if @place.save
  #     flash[:success] = "Place added!"
  #     redirect_to root_path
  #   else
  #     render 'new'
  #   end
  # end
  # def show
  #   @place = Place.find(params[:id])
  # end

  # private

  # def place_params
  #   params.require(:place).permit(:title, :raw_address, :latitude, :longitude, :visited_by)
  # end
  def index
    @places = Place.order('created_at DESC')
  end

  def new
    @place = Place.new
  end

  def create
    @place = Place.new(place_params)
    if @place.save
      flash[:success] = "Place added!"
      redirect_to root_path
    else
      render 'new'
    end
  end

  private

  def place_params
    params.require(:place).permit(:title, :address, :visited_by)
  end
end











































# class PlacesController < ApplicationController
#   def edit
#   end

#   def update
#   end

#   def index
#   end

#   def new
#   end

#   def create
#   end
# end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_form.html.erb
<%= form_for @place do |f| %>
    <fieldset class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control" %>
    </fieldset>
  
    <fieldset class="form-group">
      <%= f.label :visited_by %>
      <%= f.text_field :visited_by, class: "form-control" %>
    </fieldset>
  
    <fieldset class="form-group">
      <%= f.label :address, 'Address' %>
      <%= f.text_field :address, class: "form-control" %>
    </fieldset>
    <fieldset class="form-group">
  <%= f.label :address, 'Address' %>
  <%= f.text_field :address, class: "form-control" %>
  <small class="text-muted">You can also enter IP. Your IP is <%= request.ip %></small>
</fieldset>
  
    <%= f.submit 'Add!', class: 'btn btn-primary' %>
  <% end %>
  

  <h4>Enter either address or coordinates</h4>
<fieldset class="form-group">
  <%= f.label :raw_address, 'Address' %>
  <%= f.text_field :raw_address, class: "form-control" %>
  <small class="text-muted">You can also enter IP. Your IP is <%= request.ip %></small>
</fieldset>

<div class="form-group row">
  <div class="col-sm-1">
    <%= f.label :latitude %>
  </div>

  <div class="col-sm-3">
    <%= f.text_field :latitude, class: "form-control" %>
  </div>

  <div class="col-sm-1">
    <%= f.label :longitude %>
  </div>

  <div class="col-sm-3">
    <%= f.text_field :longitude, class: "form-control" %>
  </div>
</div>
<div class="card">
  <div class="card-block">
    <div id="map"></div>
  </div>
</div>

<div class="col-sm-3">
<%= f.text_field :longitude, class: "form-control" %>
</div>

<div class="col-sm-4">
<a href="#" id="find-on-map" class="btn btn-info btn-sm">Find on the map</a>
</div> 

app/views/places/_place.html.erb
<li>
  <%= link_to place.title, place_path(place) %>
  visited by <strong><%= place.visited_by %></strong>
</li>

app/views/places/create.html.erb
<h1>Places#create</h1>
<p>Find me in app/views/places/create.html.erb</p>

app/views/places/edit.html.erb
<h1>Places#edit</h1>
<p>Find me in app/views/places/edit.html.erb</p>

app/views/places/index.html.erb
# <h1>Places#index</h1>
# <p>Find me in app/views/places/index.html.erb</p>

<header><h1 class="display-4">Places</h1></header>

<%= link_to 'Add place', new_place_path, class: 'btn btn-primary btn-lg' %>

<div class="card">
  <div class="card-block">
    <ul>
      <%= render @places %>
    </ul>
  </div>
</div>

app/views/places/new.html.erb
# <h1>Places#new</h1>
# <p>Find me in app/views/places/new.html.erb</p>

<header><h1 class="display-4">Add Place</h1></header>

<%= render 'form' %>

app/views/places/show.html.erb
<header><h1 class="display-4"><%= @place.title %></h1></header>

<p>Address: <%= @place.address %></p>
<p>Coordinates: <%= @place.latitude %> <%= @place.longitude %></p>
<%= image_tag "http://maps.googleapis.com/maps/api/staticmap?center=#{@place.latitude},#{@place.longitude}&markers=#{@place.latitude},#{@place.longitude}&zoom=7&size=640x400&key=AIzaSyA4BHW3txEdqfxzdTlPwaHsYRSZbfeIcd8",
              class: 'img-fluid img-rounded', alt: "#{@place.title} on the map "%>

app/views/places/update.html.erb
<h1>Places#update</h1>
<p>Find me in app/views/places/update.html.erb</p>